[tool.black]
line-length = 88
target_version = ["py310"]


[tool.isort]
profile = "black"
balanced_wrapping = true
combine_as_imports = true
default_section = "THIRDPARTY"
indent = "    "
known_first_party = [
    "cdk_ecr_resource_policy",
]
