---
name: Tests
# yamllint disable rule:truthy
on: [push, workflow_dispatch]
# yamllint enable

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install AWS CDK Toolkit
        run: |
          npm install -g aws-cdk@"==2.73.0"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --no-deps \
              -r ./requirements.txt \
              -r ./requirements-dev.txt
      - name: Run black
        run: |
          python -m black --check --diff .
      - name: Run isort
        run: |
          python -m isort --check-only --diff .
      - name: Run flake8
        run: |
          python -m flake8
      - name: Synthesize CloudFormation templates
        run: |
          cdk synth cdk-ecr-resource-policy
        env:
          CDK_DISABLE_VERSION_CHECK: 1
      - name: Run cfn-lint
        run: |
          python -m cfnlint --info
